version: 2.1
jobs:
  one:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: echo "A first hello setup"
      - run: sleep 25
  two:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: echo "Second hello setup 2"
      - run: sleep 15
worksflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
