version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
  node: circleci/node@4.5.1
jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-browsers
        environment:
            TZ: Asia/Tokyo
            RAILS_ENV: test
            MYSQL_ALLOW_EMPTY_PASSWORD: true
            DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.32
        environment:
          TZ: Asia/Tokyo
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: '%'
      - image: redis
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        environment:
          - discovery.type=single-node
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - xpack.security.enabled=false
          - xpack.monitoring.enabled=false
          - xpack.graph.enabled=false
          - xpack.watcher.enabled=false
    steps:
      - checkout
      - browser-tools/install-chrome:
          chrome-version: 89.0.4389.90
      - node/install:
          install-npm: false
          install-yarn: true
          node-version: 14.5.0
      - run: |
          ruby --version
          node --version
          java --version
          google-chrome --version
          node --version
          npm --version
          yarn --version
          echo $JAVA_HOME