version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-browsers
    steps:
      - checkout
      - browser-tools/install-chrome:
          chrome-version: 92.0.4515.40
      - run: |
          ruby --version
          node --version
          java --version
          google-chrome --version